# fly.toml app configuration file generated for replantio-api-univesp on 2026-03-10T17:07:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'replantio-api-univesp'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "get"
  timeout = "5s"
  path = "/status"