# .github/workflows/ci-cd.yml
name: Pipeline Univesp (CI/CD)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testes-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: replantio_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependências e Testar
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/replantio_db
          ADMIN_EMAIL: admin@teste.com
          ADMIN_PASSWORD: senha_super_segura
          SECRET_KEY: chave_secreta_de_teste_123
        run: |
          cd backend
          pip install -r requirements.txt
          python -m pytest app/tests/

  testes-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Instalar dependências e Testar
        run: |
          cd frontend
          npm install
          npx vitest run

  deploy-gcp:
    needs: [testes-backend, testes-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Enviar arquivos para o Google Cloud (SCP)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "."
          target: "~/sistema-replantio"

      - name: Iniciar Contêineres no Servidor (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/sistema-replantio

            cat <<EOF > .env
            DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}
            ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
            ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            EOF

            cp .env backend/.env

            sudo docker compose down
            sudo docker compose up -d --build
