# .github/workflows/ci-cd.yml
name: Pipeline Univesp (CI/CD)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testes-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Instalar dependências e Testar
        run: |
          cd backend
          pip install -r requirements.txt
          python -m pytest app/tests/

  testes-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Instalar dependências e Testar
        run: |
          cd frontend
          npm install
          npx vitest run